/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#afefdd",
        "secondary-container": "#e5e2e1",
        "surface": "#fcf9f8",
        "surface-container-highest": "#e4e2e2",
        "error-container": "#fe8983",
        "on-secondary-fixed-variant": "#5c5b5b",
        "secondary-fixed": "#e5e2e1",
        "on-error": "#fff7f6",
        "surface-container-low": "#f6f3f2",
        "on-tertiary-container": "#5c5c5c",
        "on-tertiary-fixed": "#494a4a",
        "tertiary-fixed": "#f5f3f3",
        "outline": "#7b7b7a",
        "on-tertiary-fixed-variant": "#666666",
        "secondary": "#605f5f",
        "tertiary-dim": "#535353",
        "tertiary-fixed-dim": "#e7e5e4",
        "on-error-container": "#752121",
        "inverse-surface": "#0e0e0e",
        "secondary-fixed-dim": "#d6d4d3",
        "error-dim": "#4e0309",
        "primary": "#29695b",
        "tertiary-container": "#f5f3f3",
        "on-secondary-fixed": "#403f3f",
        "on-background": "#323233",
        "inverse-primary": "#bdfeeb",
        "surface-container": "#f0eded",
        "secondary-dim": "#545353",
        "on-primary-fixed-variant": "#266658",
        "inverse-on-surface": "#9e9c9c",
        "surface-bright": "#fcf9f8",
        "on-surface": "#323233",
        "on-primary-container": "#195c4e",
        "on-tertiary": "#faf8f8",
        "primary-fixed": "#afefdd",
        "background": "#fcf9f8",
        "on-secondary": "#fbf8f8",
        "tertiary": "#5f5f5f",
        "surface-dim": "#dbdad9",
        "on-surface-variant": "#5f5f5f",
        "surface-container-high": "#eae8e7",
        "primary-fixed-dim": "#a1e1cf",
        "outline-variant": "#b2b2b1",
        "surface-tint": "#29695b",
        "on-secondary-container": "#525151",
        "on-primary-fixed": "#00483c",
        "primary-dim": "#1a5c4f",
        "surface-variant": "#e4e2e2",
        "on-primary": "#defff4",
        "surface-container-lowest": "#ffffff",
        "error": "#9f403d",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
};
